server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 60
  tomcat:
    max-threads: 130
    uri-encoding: UTF-8
  
spring:
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
      additional-exclude: src/main/java
  datasource:
    url: jdbc:mysql://localhost:3306/store?useUnicode=true&characterEncoding=utf8
    username: huangqian
    password: 0805
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.hqizcc.store.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
mapper:
  mappers: com.hqizcc.store.util.MapperUtil
  not-empty: false
  identity: MYSQL
        